### Generated by ConfigEditor ###
import sys
import os.path
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_BASE','MyAnalysis/SelectionAnalysis/GridPreSelection/BackGround_WJets'))))
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_RELEASE_BASE','MyAnalysis/SelectionAnalysis'))))
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_BASE','src/MyUtilities/MyFunctions'))))
### ------------------------- ###

from topMuRefSel_cfg import *
process.setName_('GridPreSkim')
### Generated by ConfigEditor ###
if hasattr(process,'resetHistory'): process.resetHistory()
### ------------------------- ###
process.p.remove(process.step0a)
process.p.remove(process.step0b)
process.p.remove(process.step1a)
process.p.remove(process.step2)
process.p.remove(process.step3)
process.goodPatJets.preselection = cms.string('pt > 20.')
process.goodPatJets.checkOverlaps.muons.requireNoOverlaps = cms.bool(False)
process.intermediatePatMuons.preselection = cms.string('isTrackerMuon && pt > 15. && abs(eta) < 2.1 && globalTrack.normalizedChi2 < 10. && globalTrack.hitPattern.numberOfValidMuonHits > 0 && abs(dB) < 0.02 && innerTrack.numberOfValidHits > 10 && innerTrack.hitPattern.pixelLayersWithMeasurement >= 1 && numberOfMatches > 1' )#isolation is required to be less 0.2
process.loosePatMuons.checkOverlaps.jets.requireNoOverlaps = cms.bool(False)
process.loosePatMuons.preselection = cms.string('')
process.tightPatMuons.preselection = cms.string('')
process.step1b.maxNumber = 999
#process.p.remove(process.MyTTbarGenEventProd)
#process.p.remove(process.SemiLepMcFilter)
process.out.outputCommands = cms.untracked.vstring('keep *')
process.out.SelectEvents.SelectEvents += 'p'
process.source.fileNames= cms.untracked.vstring('/store/mc/Fall11/TT_TuneZ2_7TeV-mcatnlo/AODSIM/PU_S6_START42_V14B-v1/0000/027D9E4E-542A-E111-895F-0026189437FD.root')
process.out.fileName='topMuRefSel_GridPreSkim.root'
process.maxEvents.input = 10000

