### Generated by ConfigEditor ###
import sys
import os.path
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_BASE','MyAnalysis/SelectionAnalysis/GridPreSelection/BackGround_WJets'))))
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_RELEASE_BASE','MyAnalysis/SelectionAnalysis'))))
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_BASE','src/MyUtilities/MyFunctions'))))
### ------------------------- ###

from topMuRefSel_GridPreSelection_cfg import *
process.setName_('GridPreSkimTest')
### Generated by ConfigEditor ###
if hasattr(process,'resetHistory'): process.resetHistory()
### ------------------------- ###
OriginalPathP=cloneProcessingSnippet(process,process.p,"original")
process.pOriginal=cms.Path(OriginalPathP)
process.out.outputCommands = cms.untracked.vstring('drop *','keep *_TriggerResults_*_GridPreSkimTest')
process.out.SelectEvents.SelectEvents.append('pOriginal')
process.source.fileNames= cms.untracked.vstring('/store/mc/Fall11/TT_TuneZ2_7TeV-mcatnlo/AODSIM/PU_S6_START42_V14B-v1/0000/027D9E4E-542A-E111-895F-0026189437FD.root')
process.out.fileName='topMuRefSel_GridPreSelection_test.root'
process.maxEvents.input = 10000

