import sys
import os.path
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_BASE','MyAnalysis/SelectionAnalysis'))))
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_RELEASE_BASE','MyAnalysis/SelectionAnalysis'))))
### ------------------------- ###

from topMuRefSel_cfg import *

### Generated by ConfigEditor ###
if hasattr(process,'resetHistory'): process.resetHistory()
### ------------------------- ###
process.setName_('AddCollection2SelectedEvents')
print "outputCommands before: " , process.out.outputCommands
process.out.outputCommands.append('keep *_tightPatMuons_*_*')
process.out.outputCommands.append('keep *_goodPatJets_*_*')
process.out.outputCommands.append('keep *_patMETs_*_*')
process.out.SelectEvents.SelectEvents = cms.vstring('p')
process.out.fileName='topMuRefSel_AddSelectedCollections.root'
print "outputCommands ",process.out.outputCommands
