#include "FWCore/Framework/interface/MakerMacros.h"

#include "TtbarReconstructions/HypothesesFHoehle/plugins/TtSemiLepHypOwnTopMassBTag.h"
DEFINE_FWK_MODULE(TtSemiLepHypOwnTopMassBTag);
#include "TtbarReconstructions/HypothesesFHoehle/plugins/TtSemiLepHypOwnM3BTag.h"
DEFINE_FWK_MODULE(TtSemiLepHypOwnM3BTag);
#include "TtbarReconstructions/HypothesesFHoehle/plugins/TtSemiLepHypOwnPseudoMatchBJetCalcNu.h"
DEFINE_FWK_MODULE(TtSemiLepHypOwnPseudoMatchBJetCalcNu);
#include "TtbarReconstructions/HypothesesFHoehle/plugins/TtSemiLepHypOwnPseudoMatchBJetGenNu.h"
DEFINE_FWK_MODULE(TtSemiLepHypOwnPseudoMatchBJetGenNu);
#include "TtbarReconstructions/HypothesesFHoehle/plugins/TtSemiLepHypOwnPseudoMatchBJetMatchedCalcNu.h"
DEFINE_FWK_MODULE(TtSemiLepHypOwnPseudoMatchBJetMatchedCalcNu);
#include "TtbarReconstructions/HypothesesFHoehle/plugins/TtSemiLepHypOwnPseudoGenBCalcNu.h"
DEFINE_FWK_MODULE(TtSemiLepHypOwnPseudoGenBCalcNu);
#include "TtbarReconstructions/HypothesesFHoehle/plugins/TtSemiLepHypOwnPseudoGenBMatchedCalcNu.h"
DEFINE_FWK_MODULE(TtSemiLepHypOwnPseudoGenBMatchedCalcNu);


